import turtle
k=turtle.Turtle()
k.pensize(6)
k.fillcolor('red')
k.begin_fill()
k.forward(100)
k.left(90)
k.forward(100)
k.right(90)
k.backward(100)
k.left(90)
k.backward(100)
k.end_fill()
k.screen.exitonclick()
